export const reserved_keywords: string[];
export const unreserved_keywords: string[];
export const bool_literals: string[];
export const type_builtins: string[];
export const module_builtins: string[];
export const constraint_builtins: string[];
export const fn_builtins: string[];
export const operators: string[];
export const navigation: string[];