name: Test CI build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
          submodules: true

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install dev deps
        working-directory: web
        run: |
          yarn

      - name: Lint
        working-directory: web
        run: |
          yarn lint

      - name: Run build
        working-directory: web
        run: |
          yarn build
